version: '3.8'

services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack
    restart: always
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=cognito-idp,apigateway,lambda,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock # DOCKER_HOST is needed for Lambda functions to run their code
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
    networks:
      - local-services

  terraform:
    container_name: terraform
    build: ./iac
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - ./iac:/usr/src/app
    command: ["init", "&&", "tflocal", "apply", "-auto-approve"]
    networks:
      - local-services

  rage-bff:
    container_name: rage-bff
    build: ./services/rage-bff
    depends_on:
      - terraform
    ports:
      - "8080:8080"
    environment:
      - API_ENDPOINT_URL=http://localstack:4566
    networks:
      - local-services

  rage-ai:
    container_name: rage-ai
    build: ./services/rage-ai
    depends_on:
      - terraform
    ports:
      - "8000:8000"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    networks:
      - local-services

networks:
  local-services:
    driver: bridge