version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - SERVICES=cognito-idp,apigateway,lambda,dynamodb
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./.localstack:/var/lib/localstack"
    networks:
      - local-services

  terraform:
    container_name: terraform
    build: ./iac
    depends_on:
      - localstack
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    volumes:
      - ./iac:/usr/src/app
    command: sh -c "tflocal init && tflocal apply -auto-approve"
    networks:
      - local-services

  rage-bff:
    container_name: rage-bff
    build: ./services/rage-bff
    depends_on:
      - terraform
    ports:
      - "8080:8080"
    environment:
      - API_ENDPOINT_URL=http://localstack:4566
    networks:
      - local-services

  rage-ai:
    container_name: rage-ai
    build: ./services/rage-ai
    depends_on:
      - terraform
    ports:
      - "8000:8000"
    volumes:
      - ./services/rage-ai/src:/app
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - local-services

networks:
  local-services:
    driver: bridge